# Form implementation generated from reading ui file 'klasifikasitweet.ui'
#
# Created by: MorgProject
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

from PandasModel import PandasModel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableDataset = QtWidgets.QTableView(self.centralwidget)
        self.tableDataset.setGeometry(QtCore.QRect(70, 70, 661, 201))
        self.tableDataset.setObjectName("tableDataset")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 30, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnProcess = QtWidgets.QPushButton(self.centralwidget)
        self.btnProcess.setGeometry(QtCore.QRect(70, 450, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnProcess.setFont(font)
        self.btnProcess.setObjectName("btnProcess")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(350, 330, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.txtAccuracy = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAccuracy.setEnabled(False)
        self.txtAccuracy.setGeometry(QtCore.QRect(320, 360, 170, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtAccuracy.setFont(font)
        self.txtAccuracy.setObjectName("txtAccuracy")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 330, 169, 108))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.etFold = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etFold.setFont(font)
        self.etFold.setObjectName("etFold")
        self.verticalLayout.addWidget(self.etFold)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.etNeighbor = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.etNeighbor.setFont(font)
        self.etNeighbor.setObjectName("etNeighbor")
        self.verticalLayout.addWidget(self.etNeighbor)
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(320, 280, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLoad.setFont(font)
        self.btnLoad.setObjectName("btnLoad")
        self.labelImage = QtWidgets.QLabel(self.centralwidget)
        self.labelImage.setGeometry(QtCore.QRect(530, 300, 280, 210))
        self.labelImage.setText("")
        self.labelImage.setScaledContents(True)
        self.labelImage.setObjectName("labelImage")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(70, 490, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        MainWindow.setCentralWidget(self.centralwidget)

        self.btnLoad.clicked.connect(self.loadDataset)
        self.btnProcess.clicked.connect(self.process)
        self.btnClear.clicked.connect(self.clear)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "KLASIFIKASI KOMENTAR AKUN @TELKOMSEL"))
        self.label_2.setText(_translate("MainWindow", "PADA MASA COVID-19"))
        self.btnProcess.setText(_translate("MainWindow", "Proses"))
        self.label_6.setText(_translate("MainWindow", "Hasil Akurasi"))
        self.label_3.setText(_translate("MainWindow", "Jumlah K-Fold"))
        self.label_4.setText(_translate("MainWindow", "Jumlah K Neighbor"))
        self.btnLoad.setText(_translate("MainWindow", "Load Dataset"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))

    def loadDataset(self):
        filename = QFileDialog.getOpenFileName()
        self.df = pd.read_csv(filename[0], encoding='latin')
        model = PandasModel(self.df)
        self.tableDataset.setModel(model)
        self.tableDataset.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableDataset.horizontalHeader().setStretchLastSection(True)

    def process(self):
        kFold = int(self.etFold.text())
        neighbors = int(self.etNeighbor.text())
        #  Split the dataset, Training 80%, Testing 20%, Random 100x
        x_train, x_test, y_train, y_test = train_test_split(self.df.Tweet, self.df.Label, test_size=0.2,
                                                            random_state=100)

        # Initialize a TfidfVectorizer
        tfidf_vectorizer = TfidfVectorizer(max_df=0.6)
        # Fit and transform train set, transform test set
        tfidf_train = tfidf_vectorizer.fit_transform(x_train)
        tfidf_test = tfidf_vectorizer.transform(x_test)

        # Convert to Cosine Similarity
        cosine_train = cosine_similarity(tfidf_train)
        cosine_test = cosine_similarity(tfidf_test, tfidf_train)

        # Initialize a KNN
        knn = KNeighborsClassifier(n_neighbors=neighbors)
        # Fit KNN
        knn.fit(cosine_train, y_train)

        # Cross Validation with data training
        scores = cross_val_score(knn, cosine_train, y_train, cv=kFold)
        print("Mean accuracy KNN %0.2f" % (scores.mean()))

        # Predict KNN
        pred = knn.predict(cosine_test)
        # Confusion Matrix
        cf_matrix = confusion_matrix(y_test, pred)
        print(confusion_matrix(y_test, pred))
        print(classification_report(y_test, pred))
        print(accuracy_score(y_test, pred))

        self.txtAccuracy.setText(str(accuracy_score(y_test, pred)))
        sns.heatmap(cf_matrix, annot=True, fmt='', cmap='Blues')
        plt.savefig('temp.png', dpi=210)

    def clear(self):
        self.etFold.setText('')
        self.etNeighbor.setText('')
        self.txtAccuracy.setText('')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
